### ISSUE TITLE
What version of date is used?

### ISSUE THREAD

**Issue by QuLogic** [eddelbuettel/rcppdate#2]
I can't find any versions in the `date` headers or the ChangeLog. Since the initial commit is 5 months ago, I guess anywhere from v2.4.1 to a commit made around that time.

PS, v3.0.0 is available now.

**Comment by eddelbuettel** [comment]
(There must have been something odd going on with the default settings; somehow I was not following this very repo I created so I missed your issue. :disappointed: )

You know I wondered about that too when I put this together for use by `nanotime` and could not find a clear number. I will look into 3.0.0 and prepare an update when I find a moment or two.

Again, sorry for the delay!
